MULTI-STAGE build support
IBM/ibm-spectrum-scale-csi-driver pull request #17
Opened 2019-10-17 08:40 UTC by deeghuge

New docker file for multi-stage build support
README Updates

2019-10-25 10:09 UTC, smitaraut approved these changes

2019-10-25 14:00 UTC, smitaraut requested changes
The readme says "docker build -t spectrum-scale-csi:0.9.0 -f Dockerfile.msb ." whereas it should be "docker build -t csi-spectrum-scale:0.9.0 -f Dockerfile.msb ."

Also, can you include podman example too? "podman build -t csi-spectrum-scale:0.9.0 -f Dockerfile.msb ." and "podman save..."

2019-10-31 09:11 UTC, deeghuge commented
> The readme says "docker build -t spectrum-scale-csi:0.9.0 -f Dockerfile.msb ." whereas it should be "docker build -t csi-spectrum-scale:0.9.0 -f Dockerfile.msb ."
> 
> Also, can you include podman example too? "podman build -t csi-spectrum-scale:0.9.0 -f Dockerfile.msb ." and "podman save..."

@smitaraut : I have address both of your review comment. Please review the latest changes

2019-10-31 11:11 UTC, smitaraut approved these changes

2019-10-31 15:48 UTC, merged